version: "3.7"
services:
  spark-master:
    image: apache/spark:latest
    entrypoint: /opt/spark/sbin/start-master.sh
    container_name: spark-master
    environment:
      - SPARK_NO_DAEMONIZE=''
    ports:
      - 8080:8080
      - 7077:7077
  spark-worker-1:
    image: apache/spark:latest
    entrypoint: /opt/spark/sbin/start-worker.sh localhost:8080
    container_name: spark-worker-1
    depends_on:
      - spark-master    
    environment:
      - SPARK_NO_DAEMONIZE=''
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1024m      
    ports:
      - 8081:8081
  spark-worker-2:
    image: apache/spark:latest
    entrypoint: /opt/spark/sbin/start-worker.sh localhost:8080
    container_name: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - SPARK_NO_DAEMONIZE=''
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1024m  
    ports:
      - 8082:8081
